### ISSUE TITLE
Some expected diacritic glyphs are missing in name but not I think as unicodes

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/sigmarone#9]
Does it make sense to make these standard glyph name for glyphs so we can track how complete Sigmar is?

The seemingly missing glyphs are: 
cedillacomb
circumflexcomb
dieresiscomb
dotaccentcomb
ringcomb

Tcedilla
tcedilla
brevecomb
caroncomb
cedillacomb
circumflexcomb
commaaccentcomb
dieresiscomb
dotaccentcomb
hungarumlautcomb
macroncomb
ogonekcomb
ringcomb
commaturnedabovecomb

I think we are not making vietnamese support - so we don't need these but is that true?

Acircumflexgrave
acircumflexgrave
Acircumflexacute
acircumflexacute
Acircumflextilde
acircumflextilde
Acircumflexhookabove
acircumflexhookabove
Acircumflexdotbelow
acircumflexdotbelow
Abrevegrave
abrevegrave
Abreveacute
abreveacute
Abrevetilde
abrevetilde
Abrevehookabove
abrevehookabove
Abrevedotbelow
abrevedotbelow
Ahookabove
ahookabove
Adotbelow
adotbelow
Ecircumflexgrave
ecircumflexgrave
Ecircumflexacute
ecircumflexacute
Ecircumflextilde
ecircumflextilde
Ecircumflexhookabove
ecircumflexhookabove
Ecircumflexdotbelow
ecircumflexdotbelow
Etilde
etilde
Ehookabove
ehookabove
Edotbelow
edotbelow
Ihookabove
ihookabove
Idotbelow
idotbelow
Ocircumflexgrave
ocircumflexgrave
Ocircumflexacute
ocircumflexacute
Ocircumflextilde
ocircumflextilde
Ocircumflexhookabove
ocircumflexhookabove
Ocircumflexdotbelow
ocircumflexdotbelow
Ohookabove
ohookabove
Ohorngrave
ohorngrave
Ohornacute
ohornacute
Ohorntilde
ohorntilde
Ohornhookabove
ohornhookabove
Ohorndotbelow
ohorndotbelow
Odotbelow
odotbelow
Uhookabove
uhookabove
Uhorngrave
uhorngrave
Uhornacute
uhornacute
Uhorntilde
uhorntilde
Uhornhookabove
uhornhookabove
Uhorndotbelow
uhorndotbelow
Udotbelow
udotbelow
Ytilde
ytilde
Yhookabove
yhookabove
Ydotbelow
ydotbelow
brevecomb_acutecomb
brevecomb
brevecomb_gravecomb
brevecomb_hookabovecomb
brevecomb_tildecomb
circumflexcomb_acutecomb
circumflexcomb
circumflexcomb_gravecomb
circumflexcomb_hookabovecomb
circumflexcomb_tildecomb
horncomb

**Comment by aoifemooney** [comment]
hmm, strange... when I got to add these glyphs, Glyphs tells me they already exist... I'm going to hand this one over to Marc and see what is up there. =)
